% probe_fnames = {'CA_176_1', 'rec1_rec2_rec3', 1; ...
%     'CA_176_3', 'rec1_rec2_rec3', 1; ...
%     'CAA-1112416', 'rec1_rec2_rec3', 1; ...
%     'CAA-1112417', 'rec1_rec2_rec3', 1; ...
%     'CAA-1110262', 'rec1_rec2_rec3', 1; ...
%     'CAA-1110264', 'rec1_rec2', 1; ...
%     'CAA-1110265_restricted', 'rec1_rec2_rec3', 1; ...
%     'CAA-1112224', 'rec1_rec2_rec3', 1; ...
%     'CAA-1112529', 'rec1_rec2_rec3', 2; ...
%     'CAA-1112530', 'rec1_rec2_rec3', 2; ...
%     'CAA-1112531', 'rec1_rec2_rec3', 2; ...
%     'CAA-1112532', 'rec1_rec2_rec3', 2};

probe_fnames = {
    'CAA-1112211', 'rec12345', 2};

basedirs = {'F:\mateoData_probe\janelia_pipeline', ...
    'E:\mateoData_probe\janelia_pipeline'};

formatted_dir = 'C:\Users\Lee\Documents\mvelez\data\formatted_data';

n = nan(size(probe_fnames, 1), 4);

for probe_i = 1 : size(probe_fnames, 1)
    
    ks_dir = fullfile(basedirs{probe_fnames{probe_i, 3}}, ...
        probe_fnames{probe_i, 1}, ...
        'output', ...
        sprintf('catgt_%s_%s_g0', probe_fnames{probe_i, 1}, probe_fnames{probe_i, 2}), ...
        sprintf('%s_%s_g0_imec0', probe_fnames{probe_i, 1}, probe_fnames{probe_i, 2}), ...
        'imec0_ks2');
    
    spike_clusters      = read_ks_data(ks_dir, 'spike_clusters');
    cluster_ids         = sort(unique(spike_clusters));
    n(probe_i, 1)       = length(cluster_ids);
    
    output_xlsx         = fullfile(ks_dir, 'csv', 'clusters_janelia.xlsx');
    checked_clusters    = read_checked_clusters_xlsx(output_xlsx);
    n(probe_i, 2)       = size(checked_clusters, 1);
    
    selected_clusters   = read_ks_data(ks_dir, 'selected_clusters');
    n(probe_i, 3)       = length(selected_clusters);
    
    formatted_fname     = fullfile(formatted_dir, ...
        sprintf('%s_%s', probe_fnames{probe_i, 1}, probe_fnames{probe_i, 2}));
    load(formatted_fname, 'clusters');
    c                   = get_cluster_by_id(clusters, selected_clusters);
    is_cortical = ismember({c(:).region_str}, {'VISp1', 'VISp2/3', 'VISp4', 'VISp5', 'VISp6a', 'VISp6b', 'VISpX'});
    n(probe_i, 4)       = sum(is_cortical);
    
    n
end