function plot_example_mm_raster_data(h_ax, spike_times, t, mean_trace, sem_trace, fmt)

n_trials = length(spike_times);

patch(h_ax{1}, 'xdata', [0, 0.25, 0.25, 0], 'ydata', [0, 0, 1, 1], 'facecolor', [0.9, 0.9, 0.9], 'edgecolor', [0.9, 0.9, 0.9]);
set(h_ax{1}, 'xlim', t([1, end]));
axis(h_ax{1}, 'off');

if fmt.print_slip
    text(h_ax{1}, 0.125, 1.01, 'slip', 'color', 'k', 'fontsize', 6, 'horizontalalignment', 'center', 'verticalalignment', 'top');
end

for ii = 1 : n_trials
    
    scatter(h_ax{2}, spike_times{ii}, (n_trials - ii + 1) * ones(size(spike_times{ii})), ...
            scatterball_size(0.754), 'k', 'fill', 'markerfacealpha', 0.5);
end

plot(h_ax{3}, t, mean_trace, 'color', 'k', 'linewidth', 0.75);
plot(h_ax{3}, t, mean_trace+sem_trace, 'color', [0.5, 0.5, 0.5], 'linewidth', 0.25);
plot(h_ax{3}, t, mean_trace-sem_trace, 'color', [0.5, 0.5, 0.5], 'linewidth', 0.25);

ylabel(h_ax{2}, 'trial #', 'fontsize', 8)
ylabel(h_ax{3}, 'FR (Hz)', 'fontsize', 8)


%% Format
set(h_ax{2},  'clipping', 'off', ...
            'color', 'none', ...
            'fontsize', 8, ...
            'xcolor', 'none', ...
            'xlim', t([1, end]), ...
            'ylim', [0.5, n_trials+0.5], ...
            'ytick', [1, n_trials], ...
            'yticklabels', [n_trials, 1]);


set(h_ax{3},  'clipping', 'off', ...
            'color', 'none', ...
            'fontsize', 8, ...
            'xcolor', 'none', ...
            'xlim', t([1, end]), ...
            'ylim', [0, 50], ...
            'ytick', [0, 25, 50], ...
            'yticklabels', {'0', '', '50'})
